### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by TrySound** [garris/TremulaJS#16]
I like build fullsized js and css in my projects. So, maybe you will build something like this:
- Tremula.js
- Tremula.min.js
- Tremula.css
- Tremula.min.css

And put in bower main field unminified versions.

What do you think about it?

**Comment by garris** [comment]
Yes.  This is no problem.   I will see if I can do this during the week.   In the meantime, you can free to write a gulp or BASH script + pull request.

**Comment by TrySound** [comment]
Thanks. I will.. after long sleeping :)

**Comment by garris** [comment]
@TrySound  -- ok.  this is done.

**Comment by TrySound** [comment]
Thanks!
But in bower main must be just unminified files. Or both will concatenate in one.
```json
"main": [
  "dist/Tremula.js",
  "dist/Tremula.css"
]
```

**Comment by TrySound** [comment]
Also add hammer.js to dependencies. Don't know what to do with jsBezier. Seems it isn't supported. You may create helper repository with bower.json

**Comment by garris** [comment]
I am fairly certain that `main` is simply a convenience reference to key files -- Bower does not process the files in any way.   I just tested the release and got the two minified and two unminified files.  They were not concatenated.  

Also, the dependencies (hammer, jsbezier etc) are included as files in the repository (not as Bower references).  This is by design.

Thanks for your interest!

**Comment by TrySound** [comment]
I use gulp and bower-main-file for building my projects. So this is no just convenience for me.

I asked jsblumb to make bower support. It was added.

Better practice is using dependancies. Why not? Nothing will change  Just a paths.
dependancies for library and devDependancies for building

**Comment by TrySound** [comment]
> `main` *string or array:* The primary acting files necessary to use your package.
I think minified versions is unnecessary.
